version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    ports: [ '9200:9200' ]
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'