## Filebeat configuration
## https://github.com/elastic/beats/blob/master/deploy/docker/filebeat.docker.yml
#

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/lib/docker/containers/logs/*.log'
    json.keys_under_root: true

    processors:
      - decode_json_fields:
          fields: ['message']
          target: json

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: elastic
  password: 'changeme'

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

http.enabled: true
http.host: 0.0.0.0